language: python

python:
  - 2.7

env:
- DJANGO="Django>=1.4,<1.5" 
- DJANGO="Django>=1.5,<1.6" 
- DJANGO="Django>=1.6,<1.7" 
- DJANGO="Django>=1.7,<1.8"
- DJANGO="Django>=1.8,<1.9"  

install:
  - pip install mock>=1.0.1
  - pip install django-nose==1.4.1
  - pip install six==1.9.0
  - pip install -q Django==$DJANGO
  - pip install -e . 

script: ./example/manage.py test site_config
