language: python

python:
  - 2.7

env:
- DJANGO="Django>=1.4,<1.5"
- DJANGO="Django>=1.5,<1.6"
- DJANGO="Django>=1.6,<1.7"
- DJANGO="Django>=1.7,<1.8"
- DJANGO="Django>=1.8,<1.9"
- DJANGO="Django>=1.9,<1.10"

install:
  - pip install -qU $DJANGO
  - pip install -e .[testing]

script: ./example/manage.py test site_config
