language: python

python:
  - 2.7

env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8

install:
  - pip install mock>=1.0.1
  - pip install -q Django==$DJANGO
  - pip install -e . 

script: ./example/manage.py test site_config
